name: CI
on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest httpx

      - name: Train model (smoke test)
        run: python src/train_model.py

      - name: Upload metrics
        uses: actions/upload-artifact@v4
        with:
          name: metrics-v0.1
          path: metrics_v0.1.json
          if-no-files-found: ignore

      - name: Run tests
        run: pytest -q
